version: '3.9'

services:

  app:
    # build:
      # context: .
      # dockerfile: Dockerfile
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL} 
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - dbdaten:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  
  tool:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on: 
      - db

volumes:
  dbdaten: